# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true
include:		  ['_plugins']

# Setup
title:            kinbotan
tagline:          ''
description:      ''
# url:              http://hyde.getpoole.com
baseurl:          /

plugins:
  - jekyll-paginate
paginate:         5
paginate_path:    '/home/:num/'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kinbotan/kinbotan.github.io

collections:
  - japan2019
  - dummy